services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_HOST: "0.0.0.0"
        APP_PORT: ${APP_PORT}"
    image: assessment_test:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      HOST: "0.0.0.0"
      PORT: ${APP_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15.3
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
